name: Auto Merge on Success

on:
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Use your desired Java version

      - name: Build and Run Tests
        run: |
          ./mvnw clean test  # Replace with your test command

  merge:
    runs-on: ubuntu-latest
    needs: test
    if: success()  # Only run if the tests were successful

    steps:
      - name: Merge PR
        uses: "ghenao/auto-merge-action@v0.2"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
