name: Auto Merge on Push

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Use your desired Java version

      - name: Build and Run Tests
        run: |
          ./mvnw clean test  # Replace with your test command

  merge:
    runs-on: ubuntu-latest
    needs: test
    if: success() && github.ref != 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Merge to Main
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout main
          git merge ${{ github.ref }} --no-ff -m "Automated merge of ${{ github.ref }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
