name: Auto Merge on Push

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

jobs:
jobs:
  project_build:

    # Install ubuntu in the server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      # Install the java version 17 (the version of java used in springBoot demo project) in the server
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      # Set up the maven dependencies caching to use pom in the cache when the pom is non changed
      - name: Set up the Maven dependencies caching
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Install maven in the server
      - name: Install Maven dependencies
        run: mvn install

      # Run tests of the springBoot demo project
      - name: Run tests
        run: mvn --batch-mode --update-snapshots verify

  merge:
    runs-on: ubuntu-latest
    needs: test
    if: success() && github.ref != 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Merge to Main
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout main
          git merge ${{ github.ref }} --no-ff -m "Automated merge of ${{ github.ref }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
