name: Auto Merge on Push

on:
  push:
    branches:
      - '**'
jobs:
  project_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up the Maven dependencies caching
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Install Maven dependencies
        run: mvn install
      - name: Run tests
        run: mvn --batch-mode --update-snapshots verify

  merge:
    runs-on: ubuntu-latest
    needs: project_build
    if: success() && github.ref != 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Merge to Main
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout main
          git merge ${{ github.ref }} --no-ff -m "Automated merge of ${{ github.ref }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
